= Welcome to Your New Antora AsciiDoc Site!
:showtitle:
:page-title: Antora AsciiDoc Starter Guide
:page-description: A guide to get you started with your Antora site using AsciiDoc

Congratulations on setting up your Antora website powered by AsciiDoc. Your changes to the AsciiDoc content will be automatically published and hosted via Antora and GitHub.

== Next Steps

With your website up and running, you have many options to customize and expand it.

=== Editing Content

Updating your site content is straightforward. Clone your repository, open your favorite text editor, and run the content locally. Use the `antora site.yml` command and navigate to the output directory in your web browser. Antora will automatically process and display changes to your content.

You can also edit your content directly on GitHub. Navigate to the file you want to edit, click the pencil (edit) button, make your changes, and commit them. This will trigger a build process to generate and publish your updated website.

For documentation modules, Antora recognizes files in the `modules/ROOT/pages` directory and includes them in the navigation. These pages will be accessible via the `site.nav` variable.

To display a list of recent pages, use the following Antora syntax:

[source, html]
----
{% for page in site.pages limit: 5 %}
<a href="{{ page.url }}">{{ page.title }}</a>
{% endfor %}
----

=== Customizing the Look and Feel

The layout provided by Antora can be customized by editing the UI bundle. You can modify the templates and CSS files to change the appearance of your site.

=== Further Reading

For more detailed information on Antora and AsciiDoc, refer to the following resources:

* https://docs.antora.org[Antora Documentation]
* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Quick Reference]
* https://asciidoctor.org[Asciidoctor Documentation]
