site:
  title: My Documentation
  start_page: my-docs::index.adoc

content:
  sources:
    - url: .
      branches: main

ui:
  bundle:
    url: ./ui-bundle.zip  # Укажите путь к вашему UI-бандлу (или удалите эту строку, если не используете кастомный UI)

output:
  dir: ./build