site:
  title: My Documentation
  start_page: my-docs::index.adoc

content:
  sources:
    - url: .
      branches: main

output:
  dir: ./build

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true