site:
  title: My Documentation
  start_page: my-docs::index.adoc

content:
  sources:
    - url: .
      branches: main

ui:
  bundle:
    url: ./ui-bundle.zip
  start_path: .

output:
  dir: ./build