name: Build and Deploy Antora Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Глобальная установка Antora без кэширования
      - name: Install Antora
        run: npm i -g @antora/cli@3.1 @antora/site-generator@3.1

      - name: Build Antora documentation
        run: |
          antora --fetch antora-playbook.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          force_orphan: true